### ISSUE TITLE
iOS example failing using Bazel version 4.4.0

### ISSUE THREAD

**Issue by yishuiliunian** [bazelbuild/examples#206]
the error:

```

DEBUG: Rule 'build_bazel_rules_apple' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "adc96e1667416502ca87ccf888b6612821b37a3d", shallow_since = "1522244844 -0400" and dropping ["tag"]
DEBUG: Repository build_bazel_rules_apple instantiated at:
  /Users/dongzhao/temp/examples/tutorial/WORKSPACE:3:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_dongzhao/baef564110325a4d5a625796701764d5/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dongzhao/baef564110325a4d5a625796701764d5/external/build_bazel_rules_apple/apple/bundling/entitlements.bzl", line 300, column 35, in <toplevel>
		"entitlements": attr.label(
Error in label: label() got unexpected keyword argument 'single_file'
ERROR: Skipping '//ios-app:ios-app': error loading package 'ios-app': in /private/var/tmp/_bazel_dongzhao/baef564110325a4d5a625796701764d5/external/build_bazel_rules_apple/apple/ios.bzl: in /private/var/tmp/_bazel_dongzhao/baef564110325a4d5a625796701764d5/external/build_bazel_rules_apple/apple/bundling/binary_support.bzl: Extension file 'apple/bundling/entitlements.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'ios-app': in /private/var/tmp/_bazel_dongzhao/baef564110325a4d5a625796701764d5/external/build_bazel_rules_apple/apple/ios.bzl: in /private/var/tmp/_bazel_dongzhao/baef564110325a4d5a625796701764d5/external/build_bazel_rules_apple/apple/bundling/binary_support.bzl: Extension file 'apple/bundling/entitlements.bzl' has errors
INFO: Elapsed time: 0.060s
INFO: 0 processes.
```

**Comment by VegetarianZombie** [comment]
Doesn't work in bazel 5.0.0 either.

My favorite part of learning this build system is discovering all the tutorials and examples are all flat-out broken.
