### ISSUE TITLE
fatal error: 'jni.h' file not found with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/examples#393]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3566#018ccd5b-90b8-44a8-b8dc-e49718a3f330

Platform : Bazel Examples (android (Android NDK) on :mac: (OpenJDK 11, Xcode))

Logs:
```
app/src/main/cpp/native-lib.cpp:1:10: fatal error: 'jni.h' file not found
```

Steps:
```
git clone https://github.com/bazelbuild/examples.git 
git reset 36408ec43bb419d483c30cd73e08a32dd7dfefe5 --hard
export USE_BAZEL_VERSION=955b0896819ba7608d13fa6a33ba0ba9d8473004
bazel build //app/src/main:app

```

CC Greeteam @mai93

**Comment by mai93** [comment]
I think this is a duplicate of https://github.com/bazelbuild/examples/issues/381, @comius can this be caused by https://github.com/bazelbuild/bazel/commit/d8ed53897c1f0e13918a31a68b4013730a351670?
